### ISSUE TITLE
Feature Proposal: --pushstate

### ISSUE THREAD

**Issue by twilson63** [maxogden/wzrd#9]
Building SPA's, I often have the need to re-send the index.html page for other routes to leverage pushstate in the SPA.  I would like to add a cli option --pushstate that would enable `wzrd` to resend the index.html every time a request that could not be handled by ecstatic or browserify.

For example,

/widgets/1234

would render index.html instead of File Not Found if I were to start the server using:

``` sh
wzrd app.js --pushstate
```

I will be happy to submit a pull request if others would like this feature.

Thanks

Tom

**Comment by maxogden** [comment]
@twilson63 i'm not as familiar with pushstate, my apologies. can you explain what needs to change in the server code to support this? would the `--pushstate` flag force the server to always serve index.html? also what do you mean exactly by 're-send the index.js page'?

**Comment by twilson63** [comment]
> would the --pushstate flag force the server to always serve index.html? 

Yes, that is what I meant, sorry

I can send a PR, in the module.exports.static method, I would add a call back to the `staticHandler` on L46 https://github.com/maxogden/wzrd/blob/master/index.js#L46 

``` js
router.addRoute('*', function(req, res, params) {
    console.log(JSON.stringify({url: req.url, type: 'static', time: new Date()}))
    staticHandler(req, res, function() {
      if (!opts.pushstate) return fileNotFoundHandler(req, res)
      indexHtmlHandler(req,res)
    })
  })
```
Thanks

Tom

**Comment by maxogden** [comment]
@twilson63 ah ok that is pretty simple. I am still confused why the flag should be called `pushstate` though, maybe `--no-404` or `--force-index` would be more descriptive?

**Comment by twilson63** [comment]
--force-index is fine, I refer to it as pushstate because of the HTML5 pushstate api, and the server requirement to send the index.html page on any non-static request to support natural urls via a single page application vs hash urls.

ie:

/widgets/1234

vs

/#/widgets/1234

Thanks

Tom

**Comment by maxogden** [comment]
@twilson63 ahh, got it! I wasn't aware that was a *thing*. I'm okay with `--pushstate` as long as we explain it in the readme (for noobs like me)
